### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte {} in position {}: invalid start byte

### ISSUE THREAD

**Issue by aszychlinski** [cryzed/Selenium-Requests#34]
**Description:**
Any GET request attempted with this library ends in the titular error. This includes the (slightly modified) code given as an example in the documentation:

```
from seleniumrequests import Chrome
webdriver = Chrome()
response = webdriver.request('GET', 'https://www.google.com/')
```
**Environment:**
Python 3.8, PyCharm, Windows10

**STR:**

1. Run the example code
2. Check if `UnicodeDecodeError` exception is raised

**Current result:**
```
Traceback (most recent call last):
  File "C:/JetBrains/projects/PyCharm/xxxxx/test.py", line 61, in <module>
    response = webdriver.request('GET', 'https://www.google.com/')
  File "C:\JetBrains\projects\PyCharm\xxxxx\venv\lib\site-packages\seleniumrequests\request.py", line 141, in request
    self._seleniumrequests_session.headers = get_webdriver_request_headers(self)
  File "C:\JetBrains\projects\PyCharm\xxxxx\venv\lib\site-packages\seleniumrequests\request.py", line 60, in get_webdriver_request_headers
    server = BaseHTTPServer.HTTPServer(('', port), HTTPRequestHandler)
  File "C:\Program Files\Python38\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Program Files\Python38\lib\http\server.py", line 139, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Program Files\Python38\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 3: invalid start byte
```

**Comment by cryzed** [comment]
This looks like a Python/Windows 10 error, not a bug in Selenium-Requests itself. You probably have special character in your username which is causing this bug -- I can't easily fix this, sorry.
