### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by KebabLord** [cryzed/Selenium-Requests#40]
```
λ py
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from seleniumrequests import Firefox
>>> webdriver = Firefox()
>>> response = webdriver.request('GET', 'https://www.google.com/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/owo/.local/lib/python3.7/site-packages/seleniumrequests/request.py", line 166, in request
    window_handle = find_window_handle(self, condition)
  File "/home/owo/.local/lib/python3.7/site-packages/seleniumrequests/request.py", line 118, in find_window_handle
    webdriver.switch_to.window(original_window_handle)
  File "/home/owo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/switch_to.py", line 112, in window
    self._w3c_window(window_name)
  File "/home/owo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/switch_to.py", line 123, in _w3c_window
    send_handle(window_name)
  File "/home/owo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/switch_to.py", line 119, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle': h})
  File "/home/owo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/owo/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Expected "handle" to be a string, got [object Undefined] undefined

>>> 
```

**Comment by KebabLord** [comment]
updating geckodriver fixed
